# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.

version: ~> 1.0

os: linux
dist: bionic

language: node_js
node_js:
  - 12

script:
  - hostname
  - ./build.sh

notifications:
  slack:
    secure: "L4FB8CGL/VqqH91kYSHRsXALVyoOMC1EpKDA8GoHt05YeN8UmP9uLDkF8u5fduaqoqJIk0F1ZIAkB4JjR0fAC9FqMJz7c7Uxruhxr12i1AKZMivr6HqlBsTos79tlHjllBrHGdQr7dl7G3ZUErDalkleaDdKaMbUoqP2O54wn/TmZVJelWoKE0JEGJ8r/xHeF9rIbHfH3RYYj6rUMePTQ87CVtGNSalq96akB22LWid5GHKHyRB0nm+Rvz6/3p8EN2zX7FoRAyo2p6Igp25TKnxLGKJJI7X8uKQta1SMZ80VGZfPZ8rrV+rBStC0BSfeJMeQYx3tlSNd7uUO9x9MUze6v3kQLkKn/1a9M/Cqdo/TQH+RYg5y2uFbh6TP32eEllevG9Mu6Man3pFLvbzvgGCHmdShAfwrqhjDsLRFevk999RR2iB0KZSuvmSWlyWL6ODY0KWDOH9gfN502iTGXFp+moyhfkOWpRtS6oUkJjdxmoC83eOD8so0pbh6MiJ5uXrzWsUODBq354zhxIK3sLDuqEl5A8Pt/PSQemd0qPFjr4WONALy0eCo8T+rTuRTbzc9wY8QUE5u2lJcs4NYlFjpudwnzsTTuoD2JVGhX4CksqFjDr4UCgHnSUbD02Iv+uv6/wUyODYc3IbTRkyF8Hq+L++A+CevYYsiAvE2ZKg="


env:
  global:
    # SLACK_TOKEN:
    - secure: "A/uk838Bd+e40QOQRfzMaF1iuJe4Kp14Mc61qzXHJMjDmyOvG+UtWBFsIIMXGvjsTu38wQViHAEQFcNYv41z+3gcgXCu91HnWhi59hjWRbobWex2pRlpbmOpTEmbIqbMd4zZ552gksuvYYC0k9XBiYdXnTNJJK+vMeVkyyc08xRW/N9y63p9KQvJjV0/SnnlY68DFbcu12WSOwh/wBcFgcAtL5/G1egTut4zZbckXPevHi5dw4bBMRUEZ4mBARsoJfqfnRV6Y3SCoq3h2by0bnf0ljCJlVFo2iCCEXh+5oe6EgDVZeQ+qKlTAQSkXsoNAO5ZchH8ifGqGA+59F9r9IdE+y/Mj4XNm1nZ7U4fFBGlQjZ7BSct+Eiiz0cGVn31MLMZH5+bFzpV2sWXCkKpHtWNlfWHWxCQ9RYu9r1wt4KrGtFczkQWQsysrieeviffu8sIbbrCMBfVvllkgFvirMwNDydO4lk1szdKr2fRXLFw8+FW6dTqPzs2W23AdnQlaRZecy3OiMeWVHtRVPxciwJDexkoc/VBuWfWJRuKjCHdxkhi3n3CDBJ8AFLGOHh08czoipDczD0sNBERYuGwURPuj2CiGt5PO+sgnUp0Bjv2s89d2M4f2dQrLXZfpFGDVNQuKwxxh6w7seZtjjbH+qrWAZ1fouJxuav14u/GOdc="


    # GITHUB_TOKEN
    - secure: "ExwTvKvISbgm2wCMqQKRKH9feBVJqxMO3hadgQrvnAOx0Aq+zd+DGTh4PrJwMhpezp6M84wAzOCVHZgeuBZ8SXJVfGCfcnvpJ4+u3quDrDXj26kGVocXtKj50qHl2RLxv0lyOFWqzRzAs4JDwWWX7VxiorMo8vmOgZI8Q4UGAo8nDu5SFG/LDfpljo+ZbQzXa5zs9L4C8dUN+M28fw7z+LNvmaGlfVMeB197/bJBtGm7GAG4UZv60JZtwchRJZ5TVu37Xg/xH4g050qaazrIj30oFOU+p7UjxOpfPL/9RgnQngUyx7u59bFSCjPrMD8hMfPdQ2mTHSttsilf6MGAVOa5M5c27ZP0p1tW7wTn8ZvWvnAqpyxDjT9nrWW4LeAXi63oA1PNuRsn8FglUdC6rCpj7pReHK9v6cycADvpic33Z82HNXoboyQe9XuVSQVNIPXtX9DQstjERKjsknNc2+ZVtR+h6m3iC9CNUIY3HDCAcbeIcPuzdLUIPxmXRjLWplSVxSvknAiC4uQV9KiCyTkhiFXZd/UHDZhFvgWqAfqUoNEBREhnO3fxupJ9buzQlT77TdwcKpxRBOyxaQ/OWeYpcyDLlnUJLa+PTt/5/4GBj5uAtcPssG0AwOk7Dxp7vjYN3JgxMuuv20Co4kRny/pDXJRRzH+PLh4CkYqUG0U="