#.travis.yml
sudo: false

dist: trusty

language: node_js

node_js:
  - $FIREBASE_NODE_VER

install:
  - cd $TRAVIS_BUILD_DIR/doc_gen && yarn install
  - cd $TRAVIS_BUILD_DIR/doc_gen/functions && yarn install

script:
  - cd $TRAVIS_BUILD_DIR/doc_gen
  - echo $TRAVIS_NODE_VERSION
  - yarn test
  - yarn build

notifications:
  slack: louislabs:x4D51HjnR30LGpqZXrdbqUgB
